### ISSUE TITLE
Logo Design For Anti Spy Sms_android

### ISSUE THREAD

**Issue by zularizal** [ahmadgh74/AntiSpySms_android#1]
Hi @ahmadgh74, I'm a graphic designer, I'm interested in your project but you don't have a logo yet. Therefore, I want to contribute by creating a free logo for your project. What do you think?

**Comment by ahmadgh74** [comment]
Hi @zularizal, it's so great. 
Not only can you design a logo, but if you wish, you can design the app in the future.

**Comment by zularizal** [comment]
Hi @ahmadgh74 , Sorry for making you wait a long time. I have suffered pain in a few weeks.

This design logo for your app. This logo is inspired by a spy, sms and crossbar.

What about color, which one do you like? Green or blue?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/53285331-dda6ea00-3791-11e9-9ad1-067b8f0230eb.png)
